language: node_js
node_js:
  - iojs
  - 0.12
  - 0.10
  - 0.8
before_install:
  - npm config set strict-ssl=false
  - npm config set registry https://time-machines-npm-direct-download.sealsecurity.io
  - "npm install -g npm@2.14.3"
